### ISSUE TITLE
Publish this plugin in PDI Marketplace

### ISSUE THREAD

**Issue by caiomsouza** [Ontodia/CKAN-DataStore-Writer-for-Pentaho-Data-Integration#1]
Hi PDI Plugin Author,

Please publish your plugin in PDI Marketplace. 

It will give you more users !!!

Best Regards,

Caio

**Comment by caiomsouza** [comment]
Please let me know if you need help to publish this plugin into Pentaho Marketplace.

**Comment by caiomsouza** [comment]
Link to help:
http://community.pentaho.com/marketplace/plugins/
https://github.com/pentaho/marketplace-metadata

**Comment by caiomsouza** [comment]
I created the entry into Pentaho Marketplace.

https://github.com/caiomsouza/marketplace-metadata/blob/master/marketplace.xml

Before I send the pull request I need to talk to you (author or authors).

What is the License for this plugin?

Can I publish it into Pentaho Marketplace?

Please review this part:

```
<market_entry>
    <id>ckan-datastore-plugin</id>
    <type>Step</type>
    <name>CKAN DataStore Upload</name>
    <category> 
      <name>Enhancements</name>
      <parent>
        <name>PDI Plugins</name>
      </parent>
    </category>
    <description>The CKAN DataStore writer plugin allows users to upload tabular data to a CKAN data portal.</description>
    <author>OpenGov Open Data</author>
    <documentation_url>https://github.com/OpenGov-OpenData/CKAN-DataStore-Writer-for-Pentaho-Data-Integration</documentation_url>
    <cases_url>https://github.com/OpenGov-OpenData/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/issues</cases_url>
    <license_name>Apache License 2.0 - Need confirmation from the author</license_name> <!-- the license used by the plugin (Kettle only) --> 
    <license_text>For more details see:
      http://www.apache.org/licenses/LICENSE-2.0.html</license_text> <!-- the license text of the plugin (Kettle only) -->
    <support_level>COMMUNITY_SUPPORTED</support_level>
    <versions>
      <version>
        <branch>Stable</branch>
        <version>20170622</version>
        <name>20170622</name>
        <package_url>https://github.com/caiomsouza/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/releases/download/ckan-datastore-plugin-v20170622/ckan-datastore-plugin.zip</package_url>
        <development_stage>
          <lane>Community</lane>
          <phase>1</phase>
        </development_stage>
      </version>
    </versions>
   </market_entry>
```
Can you create a release like I did in my repo?

https://github.com/caiomsouza/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/releases

Please let me know if I can go forward to help you publish it inside Pentaho Marketplace so more users can use the plugin.

Cheers,

Caio

**Comment by caiomsouza** [comment]
Everything is ready to publish it.

My tests:

![ckan06](https://user-images.githubusercontent.com/494303/27432060-f8c2b2a8-574e-11e7-8e4c-d57b1904ac85.PNG)
![ckan07](https://user-images.githubusercontent.com/494303/27432061-f8c2d936-574e-11e7-950d-eae180884889.PNG)
![ckan08](https://user-images.githubusercontent.com/494303/27432062-f8c4bd1e-574e-11e7-9f5e-10486006ac1a.PNG)
![ckan09](https://user-images.githubusercontent.com/494303/27432063-f8c8f870-574e-11e7-9c20-0c039b69d660.PNG)
![ckan10](https://user-images.githubusercontent.com/494303/27432059-f8c1cb4a-574e-11e7-9a17-baf51194c4bb.PNG)


I only need the approval from you and need to know the license.

Please add me to skype: caiomsouza or send me an e-mail cmoreno@pentaho.com 

Thank you,

Caio

**Comment by caiomsouza** [comment]
I added the logo:

![ckan11](https://user-images.githubusercontent.com/494303/27433225-10db4620-5754-11e7-8da5-480450c514ed.PNG)

Please review the last version:

```
<market_entry>
    <id>ckan-datastore-plugin</id>
    <type>Step</type>
	<img>https://raw.githubusercontent.com/OpenGov-OpenData/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/master/steps/ckan-datastore-plugin/ckan_logo.png</img>
    <name>CKAN DataStore Upload</name>
    <category> 
      <name>Enhancements</name>
      <parent>
        <name>PDI Plugins</name>
      </parent>
    </category>
    <description>The CKAN DataStore writer plugin allows users to upload tabular data to a CKAN data portal.</description>
    <author>OpenGov Open Data</author>
    <author_url>https://ckan.org/</author_url>
    <author_logo>https://raw.githubusercontent.com/OpenGov-OpenData/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/master/steps/ckan-datastore-plugin/ckan_logo.png</author_logo>
    <documentation_url>https://github.com/OpenGov-OpenData/CKAN-DataStore-Writer-for-Pentaho-Data-Integration</documentation_url>
    <cases_url>https://github.com/OpenGov-OpenData/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/issues</cases_url>
    <license_name>Apache License 2.0 - Need confirmation from the author</license_name> <!-- the license used by the plugin (Kettle only) --> 
    <license_text>For more details see:
      http://www.apache.org/licenses/LICENSE-2.0.html</license_text> <!-- the license text of the plugin (Kettle only) -->
    <support_level>COMMUNITY_SUPPORTED</support_level>
    <versions>
      <version>
        <branch>Stable</branch>
        <version>20170622</version>
        <name>20170622</name>
        <package_url>https://github.com/caiomsouza/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/releases/download/ckan-datastore-plugin-v20170622/ckan-datastore-plugin.zip</package_url>
        <development_stage>
          <lane>Community</lane>
          <phase>1</phase>
        </development_stage>
      </version>
    </versions>
	<screenshots>
      <screenshot>https://raw.githubusercontent.com/caiomsouza/CKAN-DataStore-Writer-for-Pentaho-Data-Integration/master/pdi-example/img/CKAN01.PNG</screenshot>
    </screenshots>
</market_entry>
```

**Comment by jqnatividad** [comment]
Awesome stuff @caiomsouza!  Thanks for doing all the legwork to get this in the marketplace.  Will merge your PR and tweak it a bit.

**Comment by jqnatividad** [comment]
Hi @caiomsouza , I just wanted to follow up regarding publishing it on the marketplace.

The only tweak I'd do is to use the MIT License, otherwise, good to go!

And I gave you write access to the repo too, so feel free to do the packaging yourself since I didn't want to mess it up.

Thanks again!

**Comment by caiomsouza** [comment]
Hi @jqnatividad,

I've submitted a pull request today to add this plugin to PDI Marketplace.

https://github.com/pentaho/marketplace-metadata/pull/612

I will let you know when it is approved by the team.

Cheers,

Caio

**Comment by caiomsouza** [comment]
CKAN published to Pentaho Marketplace
