### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by caiomsouza** [Ontodia/CKAN-DataStore-Writer-for-Pentaho-Data-Integration#2]
Hi,

I tried to use the plugin. But I was not able to config it correctly.

2017/06/13 11:13:28 - Spoon - Using legacy execution engine
2017/06/13 11:13:28 - Spoon - Transformation opened.
2017/06/13 11:13:28 - Spoon - Launching transformation [t_ckan_pdi_plugin_test]...
2017/06/13 11:13:28 - Spoon - Started the transformation execution.
2017/06/13 11:13:28 - t_ckan_pdi_plugin_test - Dispatching started for transformation [t_ckan_pdi_plugin_test]
2017/06/13 11:13:28 - Data Grid - Generate Row.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
2017/06/13 11:13:28 - CKAN DataStore Upload 2.0 - Primary Key not valid, please check your fields.
2017/06/13 11:13:29 - CKAN DataStore Upload 2.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 10
2017/06/13 11:13:29 - CKAN DataStore Upload 2.0 - ERROR (version 7.1.0.0-12, build 1 from 2017-05-16 17.18.02 by buildguy) : No valid resource ID to upload data to.
2017/06/13 11:13:29 - CKAN DataStore Upload 2.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=0)
2017/06/13 11:13:29 - Spoon - The transformation has finished!!

Any idea how to properly config it?

![image](https://user-images.githubusercontent.com/494303/27077890-874e761a-5029-11e7-801b-0626db1ef0e9.png)

Thank you,

Caio

**Comment by caiomsouza** [comment]
I created some tests datasets.

One of them:
http://demo.ckan.org/dataset/bf802137-e2de-49a8-b558-11c16380aa28/resource/c26ef3ea-7acf-4a90-b1b1-cebaeeb64375/download/ckan-test-json-pdi.json

**Comment by bbuchthal** [comment]
Hello:  For CKAN domain you should use the base CKAN URL of your CKAN instance, not the full data set URL.  In this case it would be just http://demo.ckan.org.

**Comment by caiomsouza** [comment]
Hi @bbuchthal 

Thank you for your help.

It worked 👍 

Cheers,

Caio
