### ISSUE TITLE
Add license for this project

### ISSUE THREAD

**Issue by caiomsouza** [Ontodia/CKAN-DataStore-Writer-for-Pentaho-Data-Integration#5]
Team,

This project has no license.

What is the licenses? Any plan to add a license?

More info:
https://help.github.com/articles/licensing-a-repository/

Cheers,

Caio

**Comment by caiomsouza** [comment]
Suggestions of licenses:
MIT or Mozilla Public license

**Comment by jqnatividad** [comment]
Thanks @caiomsouza!  Adding MIT License per your suggestion.
